DEBUG = True
ASSETS_DEBUG = True
SECRET_KEY = 'no'

SITES_FOLDER = 'sites/'

SLICER_URL = 'http://129.70.40.89:3000/'

FREEZER_DESTINATION = '../build'
FREEZER_REMOVE_EXTRA_FILES = True
FLATPAGES_AUTO_RELOAD = True
